version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: artizana
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "2222:8080"  # 2222 sur localhost → 8080 dans le container Tomcat
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/artizana
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  db-data:
